# Numpy Assignment

In [ ]:
# 1. Write a function so that the columns of the output matrix are powers of the input
# vector.
# The order of the powers is determined by the increasing boolean argument. Specifically, when
# increasing is False, the i-th output column is the input vector raised element-wise to the power
# of N - i - 1.
# HINT: Such a matrix with a geometric progression in each row is named for AlexandreTheophile Vandermonde.

<img src="Vandermonde_formula.jpg">

In [56]:
import numpy as np
x = np.array([1,2,3,4,5])
N = 4
print(np.vander(x,N, True))
print(np.vander(x,N, False))

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]


In [60]:
import numpy as np
def my_vander(x, N, increasing):
    x = np.array(x, ndmin=2)
    x = x.T
    out = np.array([])
    if increasing:
        powers = range(N)
    else:
        powers = range(N-1, -1, -1)
        
    for i in powers:
        if(out.size == 0):
            out = pow(x,i)
            continue
        else:
            out = np.append(out, pow(x,i), axis=1)
    return out

x = np.array([1,2,3,4,5])
N = 4 # no. of columns
increasing = True
print( my_vander(x, N, increasing))

increasing = False
print( my_vander(x, N, increasing))

[[  1   1   1   1]
 [  1   2   4   8]
 [  1   3   9  27]
 [  1   4  16  64]
 [  1   5  25 125]]
[[  1   1   1   1]
 [  8   4   2   1]
 [ 27   9   3   1]
 [ 64  16   4   1]
 [125  25   5   1]]


-----------------------

In [ ]:
# Given a sequence of n values x1, x2, ..., xn and a window size k>0, the k-th moving average of
# the given sequence is defined as follows:
# The moving average sequence has n-k+1 elements as shown below.
# The moving averages with k=4 of a ten-value sequence (n=10) is shown below
# i 1 2 3 4 5 6 7 8 9 10
# ===== == == == == == == == == == ==
# Input 10 20 30 40 50 60 70 80 90 100
# y1 25 = (10+20+30+40)/4
# y2 35 = (20+30+40+50)/4
# y3 45 = (30+40+50+60)/4
# y4 55 = (40+50+60+70)/4
# y5 65 = (50+60+70+80)/4
# y6 75 = (60+70+80+90)/4
# y7 85 = (70+80+90+100)/4
# Thus, the moving average sequence has n-k+1=10-4+1=7 values.
# Question: Write a function to find moving average in an array over a window:
#  Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [62]:
np.cumsum([1,2,3,4,5,6,7,8,9,10])

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [72]:
x = [1,2,3,4,5,6,7]
n= len(x)
k = 3
out = np.cumsum(x)
out[k:] = out[k:] - out[:n-k] # n-k elements affected
out[k-1:]/k

array([2., 3., 4., 5., 6.])

In [85]:
def moving_avg(x, k):
    '''
    Returns the k-th moving average sequence for given inut sequence x
    
    Parameters
    ----------
    x : array like 
        input sequence
    k : int 
        k > 0 window size of moving average 
    Returns
    -------
    out : ndarray.
        A new array holding the result is returned. 
        The result has size n-k+1 elements'''
    n = len(x)
    out = np.cumsum(x)
    out[k:] = out[k:] - out[:n-k] # n-k elements affected
    return out[k-1:]/k

x = [1,2,3,4,5,6,7]
k = 3
print("For x = {} and k = {}".format(x,k))
print("Kth Moving average sequence : ")
print(moving_avg(x, k))
print("-"*50)
x = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
k = 4
print("For x = {} and k = {}".format(x,k))
print("Kth Moving average sequence : ")
print(moving_avg(x, k))
print("-"*50)
x = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
k = 3
print("For x = {} and k = {}".format(x,k))
print("Kth Moving average sequence : ")
print(moving_avg(x, k))
print("-"*50)

For x = [1, 2, 3, 4, 5, 6, 7] and k = 3
Kth Moving average sequence : 
[2. 3. 4. 5. 6.]
--------------------------------------------------
For x = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100] and k = 4
Kth Moving average sequence : 
[25. 35. 45. 55. 65. 75. 85.]
--------------------------------------------------
For x = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and k = 3
Kth Moving average sequence : 
[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
--------------------------------------------------
